# Copyright (c) 2025-2026 Zensical and contributors

# SPDX-License-Identifier: MIT
# All contributions are certified under the DCO

[package]
name = "zrx-scheduler"
version = "0.0.23"
description = "Scheduler for workflow execution"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
ahash.workspace = true
anyhow.workspace = true
crossbeam.workspace = true
thiserror.workspace = true
tracing = { workspace = true, optional = true }
zrx-diagnostic.workspace = true
zrx-executor.workspace = true
zrx-graph.workspace = true
zrx-store.workspace = true

[features]
default = []
tracing = ["dep:tracing"]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "runtime"
harness = false
